<?php

/**
 * This file is automatically generated. Use 'bin/celerity map' to rebuild it.
 *
 * @generated
 */
return array(
  'names' => array(
    'css/yadda.css' => 'a046a864',
    'js/yadda-app.min.js' => 'eb5aaf26',
    'vendor/codemirror/codemirror.css' => 'a7742522',
    'vendor/codemirror/codemirror.min.js' => 'f64c7b27',
    'vendor/codemirror/mode/coffeescript/coffeescript.min.js' => '2a057844',
    'vendor/coffeescript/coffeescript.js' => '8a9e999f',
    'vendor/lodash/lodash.js' => '216cb86c',
    'vendor/moment/moment.js' => '3ec21492',
    'vendor/react/react-dom.min.js' => '499f306a',
    'vendor/react/react.min.js' => '58873982',
  ),
  'symbols' => array(
    'codemirror' => 'f64c7b27',
    'codemirror-coffeescript' => '2a057844',
    'codemirror-css' => 'a7742522',
    'coffeescript' => '8a9e999f',
    'lodash' => '216cb86c',
    'moment' => '3ec21492',
    'react' => '58873982',
    'react-dom' => '499f306a',
    'yadda-css' => 'a046a864',
    'yadda-home' => 'eb5aaf26',
  ),
  'requires' => array(
    'a046a864' => array(
      'codemirror-css',
    ),
  ),
  'packages' => array(),
);
