<?php

/**
 * This file is automatically generated. Use 'bin/celerity map' to rebuild it.
 *
 * @generated
 */
return array(
  'names' => array(
    'yadda-home.js' => '846adcbd',
    'yadda.css' => 'c627d025',
  ),
  'symbols' => array(
    'yadda-css' => 'c627d025',
    'yadda-home-js' => '846adcbd',
  ),
  'requires' => array(),
  'packages' => array(),
);
