<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'CelerityYaddaResources' => 'res/CelerityYaddaResources.php',
    'YaddaApplication' => 'app/YaddaApplication.php',
    'YaddaHomeController' => 'app/YaddaHomeController.php',
    'YaddaQueryConduitAPIMethod' => 'api/YaddaQueryConduitAPIMethod.php',
    'YaddaSQLPatchList' => 'db/YaddaSQLPatchList.php',
    'YaddaSetStateConduitAPIMethod' => 'api/YaddaSetStateConduitAPIMethod.php',
    'YaddaUserState' => 'db/YaddaUserState.php',
  ),
  'function' => array(),
  'xmap' => array(
    'CelerityYaddaResources' => 'CelerityResourcesOnDisk',
    'YaddaApplication' => 'PhabricatorApplication',
    'YaddaHomeController' => 'PhabricatorController',
    'YaddaQueryConduitAPIMethod' => 'ConduitAPIMethod',
    'YaddaSQLPatchList' => 'PhabricatorSQLPatchList',
    'YaddaSetStateConduitAPIMethod' => 'ConduitAPIMethod',
    'YaddaUserState' => 'PhabricatorLiskDAO',
  ),
));
